---
tags: [gradle,hadoop,yarn]
projects: [spring-hadoop]
---
:spring_boot_version: 1.0.0.RC3
:jdk: http://www.oracle.com/technetwork/java/javase/downloads/index.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-gradle-yarn
This guide walks you through using Gradle to build a simple Spring YARN project.

== What you'll build

You'll create a simple app and then build it using Gradle.

NOTE: In this guide we are not trying to create fully working YARN application, instead we focus on project and build model.

== What you'll need

 - About 15 minutes
 - A favorite text editor or IDE
 - {jdk}[JDK 6] or later


include::https://raw.github.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

If you're not familiar with gradle or don't have it installed, refer to link:/guides/gs/gradle[Building Java Projects with Gradle].

[[scratch]]
== Set up the project

First you set up a Java project for Gradle to build. To keep the focus on Gradle, make the project as simple as possible for now.

include::https://raw.github.com/jvalkeal/spring-guide-work/master/macros/create_directory_structure_yarn_simple_hello.adoc[]

Firts, let's create a `ContainerApplication` class.

`src/main/java/hello/container/ContainerApplication.java`
[source,java]
----
include::complete/src/main/java/hello/container/ContainerApplication.java[]
----

Next, we create an `AppmasterApplication` class.

`src/main/java/hello/appmaster/AppmasterApplication.java`
[source,java]
----
include::complete/src/main/java/hello/appmaster/AppmasterApplication.java[]
----

The last Java class we need to create is a `ClientApplication` class.

`src/main/java/hello/client/ClientApplication.java`
[source,java]
----
include::complete/src/main/java/hello/client/ClientApplication.java[]
----

Now we need to create an `application` YAML configuration file.

`src/main/resources/application.yml`
[source,yaml]
----
include::complete/src/main/resources/application.yml[]
----

[[initial]]
== Understanding Gradle Usage with Spring YARN

We need to create a `build.gradle` file where we define everything needed for the build.

We will be using the Spring Boot Gradle plugin so `repository` and `dependency` needs to be defined within a `buildscript` section.

[source,groovy]
----
include::complete/build.gradle[tags=snippetA]
----

Belwo that section we add the following -- project version as `0.1.0` and apply plugins for `java`, `eclipse`, `idea` and `spring-boot`.

[source,groovy]
----
include::complete/build.gradle[tags=snippetB]
----

Next we add `repositories` to resolve all of the third party jar dependencies via Maven repositories.

[source,groovy]
----
include::complete/build.gradle[tags=snippetC]
----

Next, we add a dependency on Spring for Apache Hadoop project.

[source,groovy]
----
include::complete/build.gradle[tags=snippetD]
----

We use a custom `Jar` and `BootRepackage` tasks to build a client jar.
We only want to use include classes meant for `client` so we excluded
everything under `appmaster` and `container` packages.

[source,groovy]
----
include::complete/build.gradle[tags=snippetE]
----

We also create additional jars for `container` and `appmaster` using the same
logic that we used for `client`.

[source,groovy]
----
include::complete/build.gradle[tags=snippetF]
----
The Gradle plugin for `Spring Boot` automatically creates a task to
repackage a main jar file created from a project. Since we manually
created three different jar files  from a single project, it is a
good practice to disable main `jar` and `bootRepackage` tasks.

Finally, we create a simple task dependency for `build` task to depend
on `clientBoot`, `containerBoot` and `appmasterBoot` tasks. This way
all needed jar files will be build and packaged when gradle project is
built.

[source,groovy]
----
include::complete/build.gradle[tags=snippetG]
----

include::https://raw.github.com/jvalkeal/spring-guide-work/master/macros/describe_shdp_yarn_deps_gradle.adoc[]

== Build Application Packages

Run build.

[source,text]
----
gradle clean build
----

You should see three jar files created.

[source,text]
----
build/libs/gs-yarn-gradle-client-0.1.0.jar
build/libs/gs-yarn-gradle-container-0.1.0.jar
build/libs/gs-yarn-gradle-appmaster-0.1.0.jar
----

Spring Boot modifies the jars that your build creates. The original jar files are saved with a `.original` extension 
so you will see those fules in the `build\libs` directory as well. 

You can run the project with `java -jar build/libs/gs-yarn-gradle-client-0.1.0.jar` but we haven't added the code to 
actually submit the YARN application yet. So, all you will see is some logging mesages. You will build a complete
application that you can submit to YARN in the other Getting STarted Guides for Spring YARN.

== Summary

Congratulations! You have now created a simple yet effective Gradle build file for building Spring YARN projects.
