---
tags: [gradle,hadoop,yarn]
projects: [spring-hadoop]
---
:spring_boot_version: 1.0.0.RC3
:jdk: http://www.oracle.com/technetwork/java/javase/downloads/index.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-gradle-yarn
This guide walks you through using Gradle to build a simple Spring YARN project.

== What you'll build

You'll create a simple app and then build it using Gradle.

NOTE: In this guide we are not trying to create fully working YARN application, instead we focus on project and build model.

== What you'll need

 - About 15 minutes
 - A favorite text editor or IDE
 - {jdk}[JDK 6] or later


include::https://raw.github.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

If you're not familiar with gradle, refer to link:/guides/gs/gradle[Building Java Projects with Gradle].

[[scratch]]
== Set up the project

First you set up a Java project for Gradle to build. To keep the focus on Gradle, make the project as simple as possible for now.

include::https://raw.github.com/jvalkeal/spring-guide-work/master/macros/create_directory_structure_yarn_simple_hello.adoc[]

Here you create a `ContainerApplication` class.

`src/main/java/hello/container/ContainerApplication.java`
[source,java]
----
include::complete/src/main/java/hello/container/ContainerApplication.java[]
----

Here you create an `AppmasterApplication` class.

`src/main/java/hello/appmaster/AppmasterApplication.java`
[source,java]
----
include::complete/src/main/java/hello/appmaster/AppmasterApplication.java[]
----

Here you create a `ClientApplication` class.

`src/main/java/hello/client/ClientApplication.java`
[source,java]
----
include::complete/src/main/java/hello/client/ClientApplication.java[]
----

Here you create a `application` yaml configuration file.

`src/main/resources/application.yml`
[source,yaml]
----
include::complete/src/main/resources/application.yml[]
----

[[initial]]
== Understanding Gradle Usage with Spring YARN

Here you create a `gradle.build` file.

[source,groovy]
----
include::complete/build.gradle[tags=snippetA]
----

We're about to use Spring Boot Gradle plugin so `repository` and `dependency` needs to be defined within a `buildscript` section.

[source,groovy]
----
include::complete/build.gradle[tags=snippetB]
----

We defind project version to be `0.1.0` and apply plugins for `eclipse`, `idea` and `spring-boot`.

[source,groovy]
----
include::complete/build.gradle[tags=snippetC]
----

We added `repositories` to resolve maven dependencies.

[source,groovy]
----
include::complete/build.gradle[tags=snippetD]
----

We add dependency to Spring Hadoop.

[source,groovy]
----
include::complete/build.gradle[tags=snippetE]
----

We use a custom `Jar` and `BootRepackage` tasks to build a client jar.
We only want to use include classes meant for `client` so we excluded
everything under `appmaster` and `container` packages.

[source,groovy]
----
include::complete/build.gradle[tags=snippetF]
----

We created additional jars for `container` and `appmaster` using same
logic we used for `client`.

[source,groovy]
----
include::complete/build.gradle[tags=snippetG]
----

Gradle plugin for `Spring Boot` automatically creates a task to
repackage a main jar file created from a project. Because we manually
created three different jar files out from a single project, it is a
good advice to disable main `jar` and `bootRepackage` tasks.

Finally we create a simple task dependency for `build` task to depend
on `clientBoot`, `containerBoot` and `appmasterBoot` tasks. This way
all needed jar files will be build and packaged when gradle project is
built.

include::https://raw.github.com/jvalkeal/spring-guide-work/master/macros/describe_shdp_yarn_deps_gradle.adoc[]

== Build Application Packages

Run build.

[source,text]
----
./gradlew clean build
----

You should see three jar files created.

[source,text]
----
build/libs/gs-yarn-gradle-client-0.1.0.jar
build/libs/gs-yarn-gradle-container-0.1.0.jar
build/libs/gs-yarn-gradle-appmaster-0.1.0.jar
----

== Summary

Congratulations! You have now created a simple yet effective Gradle build file for building Spring YARN projects.
