spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: gs-yarn-basic-single
        applicationDir: /app/gs-yarn-basic-single/
        client:
            startup:
                action: submit
            localizer:
                patterns:
                  - "*app*jar"
            files:
              - "file:gs-yarn-basic-single-app/target/gs-yarn-basic-single-app-0.1.0.jar"
            launchcontext:
                archiveFile: gs-yarn-basic-single-app-0.1.0.jar
        appmaster:
            localizer:
                patterns:
                  - "*app*jar"
            containerCount: 1
            launchcontext:
                archiveFile: gs-yarn-basic-single-app-0.1.0.jar
                arguments:
                    --spring.profiles.active: container
