spring:
    batch:
        job:
            enabled: false
    datasource:
        url: jdbc:hsqldb:hsql://localhost:9001/testdb
        driverClassName: org.hsqldb.jdbcDriver
    yarn:
        batch:
            jobs:
              - name: job
                enabled: true
                next: true
                failNext: false
                restart: true
                failRestart: false
                parameters:
                  ? job1key1
                  : job1val1
                  ? job1key2
                  : job1val2
            job:
                enabled: true
                name: job
        appName: batch-restart-db-boot
        applicationDir: /app/batch-restart-db-boot/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        client:
            appmasterFile: gs-yarn-batch-restart-appmaster-0.1.0.jar
            files:
              - "file:build/libs/gs-yarn-batch-restart-container-0.1.0.jar"
              - "file:build/libs/gs-yarn-batch-restart-appmaster-0.1.0.jar"
        appmaster:
            waitLatch: false
            containerFile: gs-yarn-batch-restart-container-0.1.0.jar
