spring:
    batch:
        job:
            enabled: false
    yarn:
        batch:
            job:
                enabled: true
                name: job
            jobs:
              - name: job
                enabled: true
                next: true
        appName: gs-yarn-batch-processing
        applicationDir: /app/gs-yarn-batch-processing/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        client:
            appmasterFile: gs-yarn-batch-processing-appmaster-0.1.0.jar
            files:
              - "file:build/libs/gs-yarn-batch-processing-container-0.1.0.jar"
              - "file:build/libs/gs-yarn-batch-processing-appmaster-0.1.0.jar"
        appmaster:
            waitLatch: false
            containerFile: gs-yarn-batch-processing-container-0.1.0.jar
